name: Odin CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-build:
    name: Lint and Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Odin
        uses: laytan/setup-odin@v1
        with:
          odin-version: master

      - name: Install SDL2
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev

      - name: Vet and Build
        run: odin build . -vet -strict-style -vet-tabs -disallow-do -warnings-as-errors
